"""Ultralytics ↔ MLflow bridge callbacks.

Ultralytics has its own callback system: you register a function on an event
(e.g. on_fit_epoch_end) and it gets called by the trainer with the `trainer`
object. We use this to forward training metrics into our manually-managed
MLflow run.

We deliberately do NOT use Ultralytics' built-in MLflow integration because:
  1. It creates its own MLflow run that fights with ours.
  2. It can't log the Hydra config as MLflow params.
  3. It can't register the model in MLflow Model Registry.

By bridging through our own callbacks, we keep the run lifecycle in our hands.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

import mlflow

from football_tracker.training.utils import sanitize_metric_key
from football_tracker.utils.logging import get_logger

logger = get_logger()


def on_fit_epoch_end(trainer: Any) -> None:
    """Called by Ultralytics after each validation pass.

    `trainer.metrics` is a dict like:
        {
            "train/box_loss": 0.534,
            "train/cls_loss": 0.211,
            "metrics/precision(B)": 0.812,
            "metrics/recall(B)": 0.764,
            "metrics/mAP50(B)": 0.745,
            "metrics/mAP50-95(B)": 0.412,
        }
    `trainer.epoch` is the current 0-indexed epoch.
    """
    epoch = int(trainer.epoch)
    metrics = dict(trainer.metrics or {})
    if not metrics:
        return

    for key, value in metrics.items():
        try:
            clean_key = sanitize_metric_key(key)
            mlflow.log_metric(clean_key, float(value), step=epoch)
        except (ValueError, TypeError):
            # Skip non-numeric metrics gracefully
            continue


def on_train_end(trainer: Any) -> None:
    """Called once after the full training loop finishes.

    Logs the contents of the Ultralytics save directory as MLflow artifacts:
    weights/best.pt, weights/last.pt, plots (confusion matrix, PR curve, etc.).
    """
    save_dir = getattr(trainer, "save_dir", None)
    if save_dir is None:
        logger.warning("on_train_end: trainer has no save_dir, skipping artifact logging")
        return

    logger.info(f"Logging artifacts from {save_dir} to MLflow")

    # Weights
    weights_dir = save_dir / "weights"
    if weights_dir.exists():
        mlflow.log_artifacts(str(weights_dir), artifact_path="weights")

    # Plots and reports generated by Ultralytics
    for filename in [
        "confusion_matrix.png",
        "confusion_matrix_normalized.png",
        "PR_curve.png",
        "P_curve.png",
        "R_curve.png",
        "F1_curve.png",
        "results.png",
        "results.csv",
        "labels.jpg",
        "labels_correlogram.jpg",
    ]:
        f = save_dir / filename
        if f.exists():
            mlflow.log_artifact(str(f), artifact_path="plots")


def make_mlflow_callbacks() -> dict[str, Callable[[Any], None]]:
    """Return the callback map to register on a YOLO model:

    model = YOLO(...)
    for event, fn in make_mlflow_callbacks().items():
        model.add_callback(event, fn)
    """
    return {
        "on_fit_epoch_end": on_fit_epoch_end,
        "on_train_end": on_train_end,
    }
